release-date = "2024-12-31"

[[entries]]
id = "e3a86670-bb39-4619-ba18-711851919eaf"
type = "fix"
description = "Bump twine version so metadata version 2.4 is supported"
author = "uluc.sengil@helsing.ai"

[[entries]]
id = "59f38d72-bb19-4398-b358-c9c1ea3dfa59"
type = "fix"
description = "Fixes test compatibility with Poetry 2.0"
author = "thomas.pellissier-tanon@helsing.ai"

[[entries]]
id = "cef04ded-99dc-42c0-8a69-79915a368d74"
type = "improvement"
description = "Use UV as the default installer for Kraken build-time virtual environments"
author = "@NiklasRosenstein"

[[entries]]
id = "cbae7d73-09aa-442f-b099-27a4ae23b3c3"
type = "improvement"
description = "Allows to use uv with maturin"
author = "thomas.pellissier-tanon@helsing.ai"
