release-date = "2025-02-19"

[[entries]]
id = "4f5b1b3d-422f-4466-be88-2ef688bcff11"
type = "breaking change"
description = "Remove pex build task"
author = "scott@stevenson.io"

[[entries]]
id = "cac87925-0145-4281-a719-beac302c1d7e"
type = "breaking change"
description = "pytest: don't scan `src/`"
author = "antoine.broyelle@helsing.ai"

[[entries]]
id = "2c4f01f6-5d12-428f-8d36-f12a4f4dd327"
type = "fix"
description = "Clean build directory before building with uv"
author = "alexandre.ghelfi@helsing.ai"
