[[entries]]
id = "e3a86670-bb39-4619-ba18-711851919eaf"
type = "fix"
description = "Bump twine version so metadata version 2.4 is supported"
author = "uluc.sengil@helsing.ai"

[[entries]]
id = "59f38d72-bb19-4398-b358-c9c1ea3dfa59"
type = "fix"
description = "Fixes test compatibility with Poetry 2.0"
author = "thomas.pellissier-tanon@helsing.ai"
