[[entries]]
id = "5edb6a12-7001-4c4a-8fca-cf95cfd88b7b"
type = "improvement"
description = "Run CI with Python 3.13"
author = "thomas.pellissier-tanon@helsing.ai"

[[entries]]
id = "a0af4cfe-6ac0-4c38-a500-fc34b112fa3e"
type = "hygiene"
description = "Configure ruff to sort imports"
author = "scott@stevenson.io"

[[entries]]
id = "4d8a687f-14ae-4644-904a-80b1aef3421b"
type = "improvement"
description = "Support management of package indexes for uv"
author = "antoine.broyelle@helsing.ai"

[[entries]]
id = "06add927-62e1-4503-b82f-88000bd29da1"
type = "improvement"
description = "Remove `uv` as a direct dependency in kraken-build"
author = "antoine.broyelle@helsing.ai"

[[entries]]
id = "3faaa1ff-aafc-4fee-bbd6-dd91a258d483"
type = "fix"
description = "Fixes build of Maturin projects that use UV to properly build wheels using Maturin"
author = "thomas.pellissier-tanon@helsing.ai"
