[[entries]]
id = "7db61e19-eb5b-4385-a854-9523fb256d5c"
type = "deprecation"
description = "Deprecate `gitignore(gitignore_io_tokens, gitignore_io_allow_http_request_backfill)`"
author = "@NiklasRosenstein"

[[entries]]
id = "17854ad9-56e6-41a9-9d69-a4a55a830682"
type = "feature"
description = "Add `kraken.std.git.gitignore_extend()` function"
author = "@NiklasRosenstein"

[[entries]]
id = "afea35ef-4ce0-4c2e-9b25-b72d288ce6c7"
type = "breaking change"
description = "Remove `Project.do()` as it was deprecated for a long time. Use `Project.task()` instead"
author = "@NiklasRosenstein"

[[entries]]
id = "aabad4ba-ff7c-47b7-9703-5a84366b6d2b"
type = "fix"
description = "Temporarily remove @deprecated from Task.outputs; the API is actively used and we have no replacement API for it"
author = "@NiklasRosenstein"
