[[entries]]
id = "7e50c02f-8a42-4877-a64c-21fedb04dab5"
type = "refactor"
description = "Renamed `Pyproject` into `TomlFile` for better capturing what it does and moved it to `kraken.common.toml`."
author = "alexandre.ghelfi@helsing.ai"

[[entries]]
id = "00907a4a-2abe-43a5-a134-d96aaf0bdbdb"
type = "docs"
description = "Fixing typo in README"
author = "alexandre.ghelfi@helsing.ai"

[[entries]]
id = "b7f209cb-7ff7-414d-b368-bde8cb57109d"
type = "refactor"
description = "move `kraken.std.git.gitignore.parser` to `kraken.common.gitignore`"
author = "@NiklasRosenstein"
