[[entries]]
id = "5a4c9349-429d-4594-805b-404ed45020c3"
type = "improvement"
description = "Expose the `locked` property of `CargoBuildTask` via the `cargo_build` helper function"
author = "uluc.sengil@helsing.ai"
