[[entries]]
id = "0a485b7f-846f-405c-94d9-37e3717b559f"
type = "improvement"
description = "The `kraken query describe` command no longer outputs a description of _all_ tasks in the graph, but only tasks that were explicitly selected on the command-line."
author = "niklas.rosenstein@helsing.ai"
