[[entries]]
id = "c74b81bf-e59a-4b7a-9dbc-be571bb8cb88"
type = "breaking change"
description = "Remove deprecated `Project.children()` method and deprecated `Project.subproject()` overloads."
author = "@NiklasRosenstein"

[[entries]]
id = "65c94c4b-1dd5-43b8-ae97-d911b860113d"
type = "breaking change"
description = "Change `Addressable.address` into a read-only property"
author = "@NiklasRosenstein"

[[entries]]
id = "400b123c-093c-486a-8c1c-c70889bf6eac"
type = "improvement"
description = "Make `Project` a subclass of the new `KrakenObject` class"
author = "@NiklasRosenstein"

[[entries]]
id = "02f2d93b-232f-4471-8d9e-dfe05bc92ee5"
type = "deprecation"
description = "Deprecate `Project.path` and `Project.resolve_tasks()`"
author = "@NiklasRosenstein"
