[[entries]]
id = "a403dc03-77d0-4ff5-af16-70d6c8fce366"
type = "fix"
description = "Relative local dependencies in `buildscript(requirements)` are now resolved relative to the project root where `buildscript()` is called."
author = "@NiklasRosenstein"
issues = [
    "https://github.com/kraken-build/kraken/issues/263",
]
