release-date = "2022-07-20"

[[entries]]
id = "74a06257-41dd-4809-a259-5b493d2cfcc0"
type = "feature"
description = "add `BlackTask.additional_files` and `IsortTask.additional_files`"
author = "@NiklasRosenstein"

[[entries]]
id = "00ec24e0-6fb2-4179-858d-98a2eb2b79a0"
type = "fix"
description = "fix Python build system now properly moving the distributions instead of just renaming, which fails across file system boundaries"
author = "@NiklasRosenstein"
