release-date = "2022-07-20"

[[entries]]
id = "403d8b1b-c6ec-4c84-8aed-11e3cf5b2f92"
type = "improvement"
description = "Refactor Python task, add tasks for build and publish and the ability to register package indices that will be used for publishing (and should also be used for installing but we dont do that yet)"
author = "@NiklasRosenstein"

[[entries]]
id = "6974c2f9-c439-4ce1-9571-22a49ab69e0a"
type = "feature"
description = "add `kraken.std.git` module and `kraken.std.python.utils.git_version_to_python()` function"
author = "@NiklasRosenstein"
