release-date = "2022-07-19"

[[entries]]
id = "c53e0963-e23a-4723-8617-6ef690116c26"
type = "improvement"
description = "`KanikoBuildTask` now errors in `finalize()` if the `cache_repo` contains a `:` (colon)"
author = "@NiklasRosenstein"

[[entries]]
id = "b54e7e07-740f-449d-8a90-a68b795ff622"
type = "improvement"
description = "Add `SlapEnvironmentHandler` and automatic detection of an appropriate environment handler; add `InstallTask` and `install()` function to `kraken.std.python`; if the instal task exists then all toolchain tasks in Python will depend on it"
author = "@NiklasRosenstein"
