release-date = "2023-05-15"

[[entries]]
id = "cfa3781f-d873-46ff-ae6f-ae376793a832"
type = "improvement"
description = "Replace imports from `kraken.core.api` with `kraken.core` and imports of `nr.stream.Supplier` with `kraken.common.Supplier`"
author = "niklas.rosenstein@helsing.ai"
