release-date = "2022-08-22"

[[entries]]
id = "ad7dad4a-90b1-45ed-9d88-e6d9353bbb3e"
type = "improvement"
description = "kraken-core ^0.9.0 compatibility"
author = "@NiklasRosenstein"

[[entries]]
id = "94011e8e-4396-4163-a62b-4c440df82ddc"
type = "tests"
description = "improve integration tests for cargo private registries"
author = "@NiklasRosenstein"
