release-date = "2022-08-12"

[[entries]]
id = "222d56a8-ae21-43af-97f7-5947640116f0"
type = "fix"
description = "actually take the `dirty` option into account in `GitVersion.format()`"
author = "@NiklasRosenstein"

[[entries]]
id = "32d31151-2f1a-412f-a80a-d6009351d351"
type = "fix"
description = "support cargo auth proxy when Kraken build env is in PEX format"
author = "@NiklasRosenstein"
