release-date = "2022-08-14"

[[entries]]
id = "50d16673-8f7f-484b-9b78-18ddc3352ba1"
type = "fix"
description = "add `--cache-from` argument to `docker buildx build` command when `cache_repo` property is specified (in addition to the already specified `--cache-to`)"
author = "@NiklasRosenstein"
