release-date = "2023-04-12"

[[entries]]
id = "2fbbfba9-afec-458e-a77c-ac830e8ca54a"
type = "improvement"
description = "Add cargo_deny to public docs"
author = "nicolas.trinquier@helsing.ai"
pr = "https://github.com/kraken-build/kraken-std/pull/130"

[[entries]]
id = "2fbbfba9-afec-458e-a77c-ac830e8ca54b"
type = "improvement"
description = "Add docs for cargo_deny"
author = "nicolas.trinquier@helsing.ai"
pr = "https://github.com/kraken-build/kraken-std/pull/129"

[[entries]]
id = "00f364a5-e0a3-47d8-bec4-3425e71ae63b"
type = "improvement"
description = "Fix current working directory for cargo_deny"
author = "nicolas.trinquier@helsing.ai"
pr = "https://github.com/kraken-build/kraken-std/pull/131"

[[entries]]
id = "bde2dcc8-6d87-4274-b2d3-438370c93d79"
type = "fix"
description = "Rust build directory is taken from cargo-metadata instead of guessing it"
author = "daladim@users.noreply.github.com"
pr = "https://github.com/kraken-build/kraken-std/pull/133"

[[entries]]
id = "76aa3f76-06c8-4144-93ed-49bc759204f7"
type = "fix"
description = "Remove non-existing libraries as output of CargoBuild task"
author = "nicolas.trinquier@helsing.ai"
pr = "https://github.com/kraken-build/kraken-std/pull/134"

[[entries]]
id = "18ba99cd-ed86-4c2c-9b84-b606c7396c43"
type = "improvement"
description = "Support for corporate MITM filtering proxies"
author = "daladim@users.noreply.github.com"
pr = "https://github.com/kraken-build/kraken-std/pull/132"
