[[entries]]
id = "70d6a010-f261-4656-8979-62a984fe611d"
type = "improvement"
description = "Only check the active toolchain if rustup is installed"
author = "nicolas.vizzari@helsing.ai"
pr = "https://github.com/kraken-build/kraken-build/pull/38"

[[entries]]
id = "8b15ada9-8643-483c-b767-f6558279b38b"
type = "improvement"
description = "Add PDM python build system support"
author = "simone.zandara@helsing.ai"
