[project]
name = "rust-uv-project-consumer"
version = "0.1.0"
dependencies = [
    "rust-uv-project"
]
requires-python = "~=3.7"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
