[[entries]]
id = "91681271-376e-45b5-b8c3-7bf718053586"
type = "feature"
description = "Propagate `SSL_CERT_FILE` or `REQUESTS_CA_BUNDLE` environment variable to PDM repository configuration on non-Linux systems (due to https://github.com/pdm-project/pdm/issues/3076)"
author = "@NiklasRosenstein"

[[entries]]
id = "7b0576b8-d990-44c1-ab5b-395f06ab1e5f"
type = "improvement"
description = "Permit PyPI index URLs with trailing slash (e.g. `.../simple/`) in `PythonSettings.add_package_index()`"
author = "@NiklasRosenstein"
