release-date = "2023-02-15"

[[entries]]
id = "30f9f26a-d6ce-4999-928d-2de27a4287ec"
type = "improvement"
description = "allow `not_none(message)` parameter to be a callable"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/kraken-build/kraken-common/issues/2",
]
