name: "Python"

on:
  push: { branches: [ develop ], tags: [ "*" ] }
  pull_request:

jobs:


  publish:
    runs-on: ubuntu-latest
    needs: [ "test" ]
    steps:
    - uses: actions/checkout@v2
      with: { fetch-depth: 0 }
    - uses: python-slap/slap.cli@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: pip install pipx && pipx install kraken-wrapper

    - run: krakenw run publish? -0 -v
      env:
        PYPI_USER: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        TESTPYPI_USER: __token__
        TESTPYPI_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: python-slap/slap.cli@gha/install/v1
    - run: slap venv -ac && slap install --only-extras docs
    - run: slap run docs:build
    - uses: actions/upload-artifact@v2
      with: { name: docs, path: docs/_site }

  docs-publish:
    needs: [ test, docs ]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
    - uses: actions/download-artifact@v2
      with: { name: docs, path: docs/_site }
    - uses: Cecilapp/GitHub-Pages-deploy@v3
      env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
      with: { email: rosensteinniklas@gmail.com, build_dir: docs/_site }
