name: "Python"

on:
  push: { branches: [ "develop" ], tags: [ "*" ] }
  pull_request: { branches: [ "develop" ] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: NiklasRosenstein/slap@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install --link --no-venv-check
    - run: slap test

  kraken-std-integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - python-version: "3.7"
          #   test-type: integrationTest
          - python-version: "3.10"
            test-type: integrationTest

    steps:
    - uses: actions/checkout@v2
      with: { fetch-depth: 0 }
    - uses: python-slap/slap.cli@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: pip install pipx && pipx install kraken-wrapper

    # Need Poetry for integration tests.
    - run: pipx install poetry

    # Make sure we have Docker available for the ete-tests.
    - uses: docker/setup-buildx-action@v2

    - run: cd kraken-std && krakenw -vv run ${{ matrix.test-type }} -vv
      env:
        ARTIFACTORY_CARGO_REPOSITORY: ${{ vars.ARTIFACTORY_CARGO_REPOSITORY }}
        CLOUDSMITH_CARGO_REPOSITORY: ${{ vars.CLOUDSMITH_CARGO_REPOSITORY }}
        CLOUDSMITH_INTEGRATION_TEST_CREDENTIALS: |
          {
            "api_key": "${{ secrets.CLOUDSMITH_API_KEY }}",
            "owner": "${{ vars.CLOUDSMITH_OWNER }}",
            "user": "${{ vars.CLOUDSMITH_USER }}"
          }
        ARTIFACTORY_INTEGRATION_TEST_CREDENTIALS: |
          {
            "token": "${{ secrets.ARTIFACTORY_TOKEN }}",
            "url": "${{ vars.ARTIFACTORY_URL }}",
            "user": "${{ vars.ARTIFACTORY_USER }}"
          }

  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - uses: NiklasRosenstein/slap@gha/install/v1
    - run: slap install --no-venv-check --only-extras docs
    - run: slap run --no-venv-check docs:install
    - run: slap run --no-venv-check docs:build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/_site
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/develop'
      id: deployment
      uses: actions/deploy-pages@v2
